### ISSUE TITLE
chatter_concert: inconsistent problems launching additional dudes

### ISSUE THREAD

**Issue by jack-oquin** [robotics-in-concert/rocon_tutorials#18]
Testing with the hydro-devel branches.

The concert starts up well, and the various chatter messages are printed:

> rocon_launch chatter_concert chatter.concert --screen

But, launching more dudes in other shells did not work reliably on my system:

> roslaunch -p 11315 chatter_concert dude.launch --screen
> roslaunch -p 11316 chatter_concert dude.launch --screen

The first started OK, and began echoing chatter messages. The second ran for a while, but did _not_ echo any messages. I left it running, then terminated the 11315 dude. Soon after, the 11316 dude started echoing chatter messages.

That seemed cool, but after that I was not able to get either of them working again.

**Comment by stonier** [comment]
Found a couple of issues - it was supposed to repeat attempts to allocate and two things stopping that:
1. Didn't exit cleanly when allocation failed, fixed in https://github.com/robotics-in-concert/rocon_concert/issues/156
2. Wasn't repeating attempts when allocation failed - I think the callback to the scheduler used to get fired periodically? Wasn't anymore, so I had to make sure I repeat attempts to allocate until it works.

Allocation failure was simply a matter of seeing a client connect but not being able to rely on the indeterminate amount of time it takes for that client to lend the concert its /start_app handles. Rather than holding up the callback, better to just exit cleanly and repeat the attempt a while later.

At any rate, chatter concert should work for up to four clients now as specified here: https://github.com/robotics-in-concert/rocon_tutorials/blob/hydro-devel/concert_tutorials/chatter_concert/services/chatter/chatter.link_graph#L10.

I haven't got it deallocating yet, so it doesn't support intelligence when you ctrl-c clients and try to reconnect them.

**Comment by jack-oquin** [comment]
Scheduler requests should still get repeated by each requester every four seconds.

**Comment by stonier** [comment]
Ok, something odd then. Will investigate.

**Comment by stonier** [comment]
That's fine - the requester is periodic, but the scheduler callback is not:

```
    if self.rset != new_rset:       # something new?
            self.rset.merge(new_rset)
            self.sched.callback(self.rset)
```

**Comment by jack-oquin** [comment]
Right. I figured it was better to make that call only if something actually changed.

We don't have to do it that way. 

I prefer sending messages as soon as they are ready rather than waiting for the next heartbeat. The heartbeat does help if a message gets lost, but four seconds is a long time to wait before handling a request.

**Comment by jack-oquin** [comment]
The two additional dudes both run now.

But, I still can't stop one and then restart it.

**Comment by stonier** [comment]
Yeah, I'm playing around with the releasing now. Got quite busy today.

Will follow up with details in this issue: https://github.com/robotics-in-concert/rocon_concert/issues/153

**Comment by jack-oquin** [comment]
OK. I figured it was something like that, just wanted to document what works and what does not.
